services:
  - type: web
    name: airguardian-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python launch.py
    envVars:
      - key: AQICN_TOKEN
        sync: false
      - key: GEE_PROJECT
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DB_PATH
        value: /data/airguardian.db
    disk:
      name: airguardian-data
      mountPath: /data
      sizeGB: 1
